### ISSUE TITLE
Add products

### ISSUE THREAD

**Issue by indyger** [johnwayne1930/FS22_PalletStorageLogistic#4]
Hi and thank your for this great mod!

I try to add some products for our multiplayer game, but i don't get it :/. I want to add the product "PAPERS", i added it on every entry, like the other products to, and when i connect to the server, the mod is inactive, the building is not rendered...

Can you please give me an hint?

Best regards!

**Comment by johnwayne1930** [comment]
Hi, 
should be pretty simple an entry in `<productionPoint>` like this
```
            <production id="papers" name="$l10n_fillType_papers" cyclesPerHour="1000" costsPerActiveHour="0">
                <inputs>
                    <input fillType="PAPERS" amount="1" />
                </inputs>
                <outputs>
                    <output fillType="PAPERS" amount="1" />
                </outputs>
            </production>
```
And add the line like this under `<storage ...>`
`<capacity fillType="PAPERS"       capacity="100000" />
`
Also you have to add the PAPERS as filltypes in `<sellingStation...>`

If the Multiplayer issue persists you can upload a logfile here and I take a look for a cause.

**Comment by indyger** [comment]
Thank you for your fast reply! In conclusion: Now it works!

I did it the way, you described (this was my intention too). The errorous part, was that i renamed the file, so, that i always have the original and "my" version. The filname need to be the original, otherwise, the mod won't work on multiplayer. I don't know why, on another mod, i did the same and it worked. But thats not a problem, it's juste good to know.

In the end, their is a little error message, which don't seem to affect the function of the mod.

Again, thank you alot for the fast help an verification of my process!

![grafik](https://github.com/johnwayne1930/FS22_PalletStorageLogistic/assets/134952730/45369ffd-b1b5-46d5-ac83-3260412018ce)

**Comment by johnwayne1930** [comment]
Renaming the mod would work if the building was not already built on the map and all other players on the server have the same filename. 
Generally tho it is never a good idea to rename modfiles, some depend on their name, especially some script mods.

For the error message, it indicates that a translation of the filltype is missing, but as you said it should not affect the mods functionality.
